In [49]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

df = pd.read_csv(r'E:\ML\PROJECT\PRACTICE\SBI STOCK\SBI_BANK.csv')
df.dropna(inplace=True)
df

,Date,Open,High,Low,Close,Adj Close,Volume,VWAP
0,03-01-2000,22.267092,22.988886,22.101974,22.988886,16.110510,25152894.0,22.69324867
1,04-01-2000,22.988886,24.720245,22.535995,24.446625,17.132088,47648560.0,23.900955
2,05-01-2000,23.493668,24.974997,23.116261,23.441774,16.427893,36396207.0,23.844344
3,06-01-2000,23.776726,25.286358,23.776726,24.625893,17.257719,70573968.0,24.56299233
4,07-01-2000,24.673071,26.409147,24.059780,25.786425,18.071014,83453217.0,25.41845067
...,...,...,...,...,...,...,...,...
5868,19-06-2023,571.250000,572.750000,565.900024,568.849976,568.849976,17903691.0,569.1666667
5869,20-06-2023,568.849976,569.450012,562.549988,567.400024,567.400024,14549152.0,566.4666747
5870,21-06-2023,567.400024,569.500000,565.650024,566.349976,566.349976,14946871.0,567.1666667
5871,22-06-2023,566.349976,569.000000,561.049988,562.950012,562.950012,14979063.0,564.3333333
5872,23-06-2023,562.000000,562.099976,553.799988,554.599976,554.599976,12215712.0,556.8333133

In [50]:
# x = df['Open']
# y = df['Close']

# plt.plot(x,y)
# plt.show()

In [51]:
# from sklearn import linear_model
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import r2_score
# from sklearn.metrics import mean_absolute_error
# sbi = linear_model.LinearRegression()
# sbi.fit(df[['Open']],df['Close'])

In [52]:
# pred = sbi.predict([[598.700000]])
# print(pred)
# print("Predicted Close Price:", pred[0])
# # print("Accuracy Score :",r2_score(y, sbi.predict(x)))
# # print("Mean Absolute Error (MAE):", mean_absolute_error(test_y, sbi.predict(test_x)))

In [53]:
# x = df[['Open']]
# y = df[['Close']]

# train_x, test_x, train_y, test_y = train_test_split(x, y, random_state=0)

# sbi = linear_model.LinearRegression()
# sbi.fit(train_x, train_y)

# pred = sbi.predict([[594.100000]])
# print("Predicted Close Price:", pred[0])  # Access the first element of the prediction array
# print("Accuracy Score:", r2_score(test_y, sbi.predict(test_x)))
# print("Mean Absolute Error (MAE):", mean_absolute_error(test_y, sbi.predict(test_x)))

In [54]:
# #Implementation In Decision Tree
# from sklearn.tree import DecisionTreeRegressor
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import r2_score


# features = ['Open', 'Volume', 'VWAP']
# X = df[features]
# y = df['Close']


# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# sbi = DecisionTreeRegressor(random_state=42)


# sbi.fit(X_train, y_train)


# y_pred = sbi.predict(X_test)


# r2 = r2_score(y_test, y_pred)

# print("R^2 score:", r2)

# print("Mean Absolute Error(MAE) : ", mean_absolute_error(y_test,y_pred))

In [55]:
# from sklearn.ensemble import RandomForestRegressor

In [56]:
# from sklearn.model_selection import train_test_split
# from sklearn.ensemble import RandomForestRegressor

# # Define the features and target variable
# features = ['Open', 'Volume', 'VWAP']  # Remove inner list
# X = df[features]
# y = df['Close']

# # Split the data into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# # Initialize the RandomForestRegressor with corrected parameters
# sbi = RandomForestRegressor(n_estimators=30, random_state=42)

# # Train the model
# sbi.fit(X_train, y_train)

# # Make predictions
# y_pred = sbi.predict(X_test)

In [57]:
# r2 = r2_score(y_test, y_pred)

# print("R^2 score:", r2)

# print("Mean Absolute Error(MAE) : ", mean_absolute_error(y_test,y_pred))

# KNN

In [68]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
# Define the features and target variable
features = ['Open', 'Volume', 'VWAP']  # Remove inner list
X = df[features]
y = df['Close']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize the RandomForestRegressor with corrected parameters
sbi = KNeighborsRegressor(1000)

# Train the model
sbi.fit(X_train, y_train)

# Make predictions
y_pred = sbi.predict(X_test)

In [69]:
r2 = r2_score(y_test, y_pred)

print("R^2 score:", r2)

print("Mean Absolute Error(MAE) : ", mean_absolute_error(y_test,y_pred))

R^2 score: 0.07633940875095002
Mean Absolute Error(MAE) :  108.37005130174772